import baseCard from './baceCard'
import StateCard from "./StateCard/index.vue";
import MeasureCard from "./MeasureCard/index.vue"
import testTable from './MeasureCard/tete'
import cardTable from './MeasureCard/CardTable';
const CardTable =  cardTable
const BaseCard = baseCard
const TestTable = testTable
export {BaseCard, StateCard, MeasureCard,TestTable,CardTable}